"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";
import Leftnav from "@/components/Leftnav/leftnav"; // ✅ Use uppercase for components
import { usePathname } from "next/navigation"; // ✅ Get the current route

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current route

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <Toaster position="bottom-left" reverseOrder={false} />

          {/* Show LeftNav on all pages except /dashboard */}
          <div className="flex">
            {pathname !== "/" && <Leftnav />} 

            {/* Main Content */}
            <main className={`flex-1 ${pathname !== "/" }`}>
              {children}
            </main>
          </div>
          
        </StoreProvider>
      </body>
    </html>
  );
}
